config/routes.rb
Rails.application.routes.draw do
  get 'rsvps/create'
  get 'rsvps/destory'
  get 'rsvps/update'
  get 'user/index'
  get 'user/show'
  devise_for :users
  resources :users, :only => [:show]
  resources :events
  root 'events#index'
  devise_scope :user do
    get '/user/sign_out' => 'devise/sessions#destroy'
 end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :creator, class_name: "User", foreign_key: "user_id"
  has_many :rsvps
  has_many :attendees, through: :rsvps, source: :user

  scope :future, -> { where('date > ?', Time.now) }
  scope :past,   -> { where('date < ?', Time.now) }
  # Ex:- scope :active, -> {where(:active => true)}
end

app/models/rsvp.rb
class Rsvp < ApplicationRecord
  belongs_to :event
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :events, inverse_of: :creator
  has_many :rsvps
  has_many :attended_events, through: :rsvps, source: :event
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: %i[ show edit update destroy ]

  # GET /events or /events.json
  def index
    @events = Event.all
    @future_events = Event.future
    @past_events = Event.past
    if user_signed_in?
      @rsvp = Rsvp.find_by(event_id: params[:event_id], user_id: current_user.id)
    end
  end

  # GET /events/1 or /events/1.json
  def show
    @event = Event.find(params[:id])
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events or /events.json
  def create
    @event = current_user.events.build(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to event_url(@event), notice: "Event was successfully created." }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1 or /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to event_url(@event), notice: "Event was successfully updated." }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1 or /events/1.json
  def destroy
    @event.destroy!

    respond_to do |format|
      format.html { redirect_to events_url, notice: "Event was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def event_params
      params.require(:event).permit(:name, :description, :location, :date)
    end
end

app/controllers/rsvps_controller.rb
class RsvpsController < ApplicationController
    before_action :require_login

  def create
    event = Event.find(params[:id])
    rsvp = Rsvp.new(event_id: event.id, current_user_id: params(:id))

    if rsvp.save
      rsvp.invited!
      flash[:notice] = "RSVP Sent!"
      redirect_to users_path(event_id: event.id)
    else
      flash[:alert] = "RSVP unsuccessful"
      redirect_to event_path(event)
    end
  end

  def destory
    event = Event.find(params[:event_id])
    rsvp = Rsvp.find(params[:id])
    if current_user == event.creator
      rsvp.destroy
      flash[:notice] = "The RSVP was cancelled"
    else
      rsvp.invited!
      flash[:notice] = "You have been dropped from the #{event.name}"
    end

    redirect_to users_path(event_id: event.id, id: rsvp.id)
  end

  def update
    @event = Event.find(params[:event_id])
    @rsvp = Rsvp.find_by(event_id: params[:event_id], user_id: current_user.id)
    if @rsvp && @rsvp.invited?
      @rsvp.accepted!
        flash[:notice] = "Thank you for signing up for #{@event.name}"
    else
      flash[:alert] = "Your name is not on the invite list."
    end
    redirect_to event_path(@event)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @future_events = Event.future
    @past_events = Event.past
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/rsvps_helper.rb
module RsvpsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/events/_event.html.erb
<div id="<%= dom_id event %>">
  <p>
    <strong>Name:</strong>
    <%= event.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= event.description %>
  </p>

  <p>
    <strong>Location:</strong>
    <%= event.location %>
  </p>

  <p>
    <strong>Date:</strong>
    <%= event.date %>
  </p>

</div>

app/views/events/_form.html.erb
<%= form_with(model: event) do |form| %>
  <% if event.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
        <% event.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description %>
  </div>

  <div>
    <%= form.label :location, style: "display: block" %>
    <%= form.text_field :location %>
  </div>

  <div>
    <%= form.label :date, style: "display: block" %>
    <%= form.date_field :date %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing event</h1>

<%= render "form", event: @event %>

<br>

<div>
  <%= link_to "Show this event", @event %> |
  <%= link_to "Back to events", events_path %>
</div>

app/views/events/index.html.erb
<p style="color: green"><%= notice %></p>

<h2>Upcoming Events</h2>
<% @future_events.each do |event| %>
  <%= render event %>
  <% if event.creator == current_user %>
    <%= button_to "Invite", user_index_path, params: { event_id: event.id }, method: :get %>
  <% else %>
    <% @rsvp %>
    <% if @rsvp && @rsvp.accepted? %>
      <%= button_to "Cancel RSVP", rsvp_path(id: rsvp.id, event_id: event.id, user_id: current_user.id), method: :delete %>
    <% else %>
      <%= button_to "RSVP", rsvps_update_path(event_id: event.id), method: :post %>
    <% end %>
  <% end %>
<% end %>

<h2>Past Events</h2>
<ul>
  <% @past_events.each do |event| %>
    <li><%= event.name %> - <%= event.date %></li>
  <% end %>
</ul>


<%= link_to "New event", new_event_path %>

<h1>Event History</h1>

<div id="events">
  <% @events.each do |event| %>
    <%= render event %>
    <p>
      <%= link_to "Show this event", event %>
    </p>
      
  <% end %>
</div>

app/views/events/new.html.erb
<h1>New event</h1>

<%= render "form", event: @event %>

<br>

<div>
  <%= link_to "Back to events", events_path %>
</div>

app/views/events/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @event %>

<p>Hosted by </p>
<h4><%= @event.creator.email %></h4>

<h3>Attendees:</h3>
<ul>
  <% @event.attendees.each do |attendee| %>
    <li><%= attendee.email %></li> <li><%= attendee.id %></li>
  <% end %>
</ul>

<div>
  <%= link_to "Edit this event", edit_event_path(@event) %> |
  <%= link_to "Back to events", events_path %>

  <%= button_to "Destroy this event", @event, method: :delete %>
</div>

<% if @event.creator == current_user %>
  <%= button_to "Invite", user_index_path, params: {:event_id => @event.id}, method: :get %>
  <% else %>
  <% if rsvp && rsvp.accepted? %>
    <%= button_to "Cancel RSVP", rsvp_path(id: rsvp.id, event_id: @event.id, user_id: current_user.id), method: :delete %>
  <% else %>
  <%= button_to "RSVP", rsvp_path(event_id: @event.id), method: :post %>
  <% end %>
<% end %>

app/views/layouts/_nav.html.erb
<nav>
  <% if user_signed_in? %>
    <ul>
      <!-- Displayed when user is logged in -->
      <li><%= link_to 'Create Event', new_event_path %></li>
      <li><%= link_to 'View Events', events_path %></li>
      <li><%= link_to "View Profile", current_user %></li>
      <li><%= link_to 'Edit Profile', edit_user_registration_path %></li>
      <li><%= button_to 'Logout', destroy_user_session_path, method: :delete %></li>
      <!-- Display User Info -->
      <li><%= current_user.email %></li>
    </ul>
  <% else %>
    <ul>
      <!-- Displayed when user is not logged in -->
      <li><%= link_to 'Sign In', new_user_session_path %></li>
      <li><%= link_to 'Sign Up', new_user_registration_path %></li>
    </ul>
  <% end %>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEventsDec3</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'layouts/nav' %>
    <%= yield %>
  </body>
</html>

app/views/rsvps/create.html.erb
<h1>Rsvps#create</h1>
<p>Find me in app/views/rsvps/create.html.erb</p>

app/views/rsvps/destory.html.erb
<h1>Rsvps#destory</h1>
<p>Find me in app/views/rsvps/destory.html.erb</p>

app/views/rsvps/update.html.erb
<h1>Rsvps#update</h1>
<p>Find me in app/views/rsvps/update.html.erb</p>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
  <p>
    <strong>Name:</strong>
    <%= user.email %>
  </p>

</div>

app/views/users/index.html.erb
<% @users.each do |user| %>
    <%= render 'user', user: user %>
<% end %>

app/views/users/show.html.erb
<h1>👋Welcome to your profile <%= @user.email %> </h1>


<h3>Total Attended Events:</h3>
<ul>
  <% @user.attended_events.each do |attended_events| %>
    <li><%= attended_events.id %></li> 
  <% end %>
</ul>

<h2>Upcoming Events</h2>
<ul>
  <% @future_events.each do |event| %>
    <li><%= event.name %> - <%= event.date %></li>
  <% end %>
</ul>

<h2>Past Events</h2>
<ul>
  <% @past_events.each do |event| %>
    <li><%= event.name %> - <%= event.date %></li>
  <% end %>
</ul>